import Link from "next/link";
import { notFound } from "next/navigation";
import { and, eq } from "drizzle-orm";
import { opportunityToContentAction, setOpportunityStatusAction, toggleOpportunityActionStep } from "@/app/actions/growth";
import { Badge, Button, Flash, HiddenBack, KV, PageHeader, Panel, PotentialBadge, StatusBadge } from "@/components/ui";
import { opportunities, products, queries } from "@/db/schema";
import { pageData, type SP } from "@/lib/page";
import { enumLabel } from "@/i18n/core";
import { getI18n, getT } from "@/i18n/server";
import type { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getT();
  return { title: t("Opportunity") };
}

export default async function OpportunityDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<SP> }) {
  const { id } = await params;
  const sp = await searchParams;
  const { t } = await getI18n();
  if (!/^[0-9a-f-]{36}$/.test(id)) notFound();
  const { data, can } = await pageData(async (tx, ctx) => {
    const o = await tx.query.opportunities.findFirst({ where: and(eq(opportunities.id, id), eq(opportunities.organizationId, ctx.org.id)) });
    if (!o) notFound();
    const product = o.productId ? await tx.query.products.findFirst({ where: eq(products.id, o.productId) }) : null;
    const query = o.queryId ? await tx.query.queries.findFirst({ where: eq(queries.id, o.queryId) }) : null;
    return { o, product, query };
  });
  const { o } = data;
  const back = `/opportunities/${id}`;
  return (
    <>
      <PageHeader eyebrow={t("Opportunity · {product}", { product: data.product?.name ?? t("Ecosystem") })} title={t(o.title)} description={t(o.problem)} actions={<Link className="eyebrow hover:text-chrome" href="/opportunities">{t("← All")}</Link>} />
      <Flash searchParams={sp} />
      <div className="grid gap-6 lg:grid-cols-[1fr_22rem]">
        <div className="flex flex-col gap-6">
          <Panel title={t("Recommended actions")} eyebrow="Plan">
            <ol className="flex flex-col gap-2">
              {o.actions.map((a) => (
                <li key={a.order}>
                  <form action={toggleOpportunityActionStep} className="flex items-start gap-3">
                    <HiddenBack path={back} />
                    <input type="hidden" name="id" value={o.id} />
                    <input type="hidden" name="order" value={a.order} />
                    <button disabled={!can("growth:write")} className={`mt-0.5 h-4 w-4 shrink-0 border ${a.done ? "border-ok bg-ok/30" : "border-line-strong"}`} aria-label={a.done ? t("Mark not done") : t("Mark done")} />
                    <span className={`text-sm ${a.done ? "text-muted line-through" : "text-platinum"}`}>
                      <span className="num mr-2 text-muted">{a.order}.</span>
                      {t(a.action)}
                    </span>
                  </form>
                </li>
              ))}
            </ol>
          </Panel>
          <Panel title={t("Evidence")} eyebrow={t("Why Beacon suggests this")}>
            <KV items={o.evidence.map((e) => [t(e.label), t(e.value)])} />
            {o.competitors.length > 0 && (
              <div className="mt-4">
                <div className="eyebrow mb-1">{t("Competitors appearing")}</div>
                <div className="flex flex-wrap gap-1">
                  {o.competitors.map((c) => (
                    <Badge key={c}>{c}</Badge>
                  ))}
                </div>
              </div>
            )}
          </Panel>
        </div>
        <div className="flex flex-col gap-6">
          <Panel title={t("Assessment")}>
            <div className="flex flex-wrap gap-2">
              <PotentialBadge potential={o.potential} />
              <StatusBadge status={o.status} />
            </div>
            <div className="mt-4">
              <KV items={[[t("Impact"), `${o.impact}/5`], [t("Confidence"), `${o.confidence}/5`], [t("Effort"), `${o.effort}/5`], [t("Urgency"), `${o.urgency}/5`], [t("Priority"), String(o.priorityScore)], [t("Query"), data.query?.query ?? null], [t("Generated by"), t(o.generatedBy)], [t("Updated"), o.updatedAt.toISOString().slice(0, 10)]]} />
            </div>
          </Panel>
          {can("content:write") && o.productId && (
            <Panel title={t("Act on it")} eyebrow={t("Content studio")}>
              <form action={opportunityToContentAction} className="flex flex-col gap-3">
                <HiddenBack path={back} />
                <input type="hidden" name="id" value={o.id} />
                <select name="type" defaultValue={o.type === "COMPARISON_FACTS" ? "COMPARISON" : o.type === "AI_VISIBILITY_GAP" ? "FAQ" : "LANDING_PAGE"} aria-label={t("Format")}>
                  {["LANDING_PAGE", "ARTICLE", "FAQ", "TUTORIAL", "COMPARISON"].map((ty) => (
                    <option key={ty} value={ty}>
                      {enumLabel(t, ty)}
                    </option>
                  ))}
                </select>
                <div>
                  <Button variant="gold">{t("Generate draft")}</Button>
                </div>
              </form>
            </Panel>
          )}
          {can("growth:write") && (
            <Panel title={t("Status")}>
              <form action={setOpportunityStatusAction} className="flex flex-wrap gap-2">
                <HiddenBack path={back} />
                <input type="hidden" name="id" value={o.id} />
                {(["ACCEPTED", "IN_PROGRESS", "DONE", "DISMISSED", "OPEN"] as const)
                  .filter((s) => s !== o.status)
                  .map((s) => (
                    <Button key={s} name="status" value={s}>
                      {enumLabel(t, s)}
                    </Button>
                  ))}
              </form>
            </Panel>
          )}
        </div>
      </div>
    </>
  );
}
